// 2020-04-24T12:05:42.553-07:00 binding hdr_histogram.c (GenerateDeclarations)
// Generated by inspiredware's Binding Toolkit — www.inspiredware.com

#include <napi.h>

// pseudoClass HdrHistogram declaration begin //
#include <hdr_histogram.h>; // from the origin library

class HdrHistogram : public Napi::ObjectWrap<HdrHistogram> {
 public:
  HdrHistogram(const Napi::CallbackInfo& info);
  ~HdrHistogram();
  static Napi::Object Init(Napi::Env env, Napi::Object exports);

 private:
  Napi::Value hdr_reset_internal_counters_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_init_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_close_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_reset_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_get_memory_size_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_value_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_value_atomic_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_values_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_values_atomic_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_corrected_value_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_corrected_value_atomic_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_corrected_values_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_record_corrected_values_atomic_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_add_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_max_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_min_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_value_at_percentile_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_mean_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_stddev_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_values_are_equivalent_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_lowest_equivalent_value_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_count_at_value_binding (const Napi::CallbackInfo& info);

  hdr_histogram* histogram;
};
// pseudoClass HdrHistogram declaration end //
// pseudoClass HdrHistogramIterator declaration begin //
#include <hdr_histogram.h>; // from the origin library

class HdrHistogramIterator : public Napi::ObjectWrap<HdrHistogramIterator> {
 public:
  HdrHistogramIterator(const Napi::CallbackInfo& info);
  ~HdrHistogramIterator();
  static Napi::Object Init(Napi::Env env, Napi::Object exports);

 private:
  Napi::Value hdr_iter_init_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_iter_next_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_iter_percentile_init_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_iter_recorded_init_binding (const Napi::CallbackInfo& info);
  Napi::Value hdr_iter_linear_init_binding (const Napi::CallbackInfo& info);

  hdr_iter* iter;
};
// pseudoClass HdrHistogramIterator declaration end //