// 2020-04-24T12:05:42.876-07:00 binding hdr_histogram.c (GenerateDefinitions)
// Generated by inspiredware's Binding Toolkit — www.inspiredware.com

#include "hdr_histogram.h"
#include "napi-ingress.h"

extern "C" {
}
// pseudoClass HdrHistogram definition begin //

Napi::Value HdrHistogram::hdr_reset_internal_counters_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  hdr_reset_internal_counters (h);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_init_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  long long lowest_trackable_value = getNumber<long long> (info, 0);
  long long highest_trackable_value = getNumber<long long> (info, 1);
  int significant_figures = getNumber<int> (info, 2);
  struct hdr_histogram ** result;
  int retVal = hdr_init (lowest_trackable_value, highest_trackable_value, significant_figures, result);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_close_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  hdr_close (h);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_reset_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  hdr_reset (h);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_get_memory_size_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  unsigned long retVal = hdr_get_memory_size (h);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_value_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  _Bool retVal = hdr_record_value (h, value);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_value_atomic_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  _Bool retVal = hdr_record_value_atomic (h, value);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_values_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long count = getNumber<long long> (info, 2);
  _Bool retVal = hdr_record_values (h, value, count);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_values_atomic_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long count = getNumber<long long> (info, 2);
  _Bool retVal = hdr_record_values_atomic (h, value, count);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_corrected_value_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long expected_interval = getNumber<long long> (info, 2);
  _Bool retVal = hdr_record_corrected_value (h, value, expected_interval);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_corrected_value_atomic_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long expected_interval = getNumber<long long> (info, 2);
  _Bool retVal = hdr_record_corrected_value_atomic (h, value, expected_interval);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_corrected_values_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long count = getNumber<long long> (info, 2);
  long long expected_interval = getNumber<long long> (info, 3);
  _Bool retVal = hdr_record_corrected_values (h, value, count, expected_interval);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_record_corrected_values_atomic_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long count = getNumber<long long> (info, 2);
  long long expected_interval = getNumber<long long> (info, 3);
  _Bool retVal = hdr_record_corrected_values_atomic (h, value, count, expected_interval);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_add_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_histogram * h = 0;
  const struct hdr_histogram * from = 0;
  long long retVal = hdr_add (h, from);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_max_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  long long retVal = hdr_max (h);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_min_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  long long retVal = hdr_min (h);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_value_at_percentile_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  float percentile;
  long long retVal = hdr_value_at_percentile (h, percentile);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_mean_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  double retVal = hdr_mean (h);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_stddev_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  double retVal = hdr_stddev (h);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_values_are_equivalent_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  long long a = getNumber<long long> (info, 1);
  long long b = getNumber<long long> (info, 2);
  _Bool retVal = hdr_values_are_equivalent (h, a, b);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_lowest_equivalent_value_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long retVal = hdr_lowest_equivalent_value (h, value);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}

Napi::Value HdrHistogram::hdr_count_at_value_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  const struct hdr_histogram * h = 0;
  long long value = getNumber<long long> (info, 1);
  long long retVal = hdr_count_at_value (h, value);
  Napi::Value jsRetVal = Number::New(env, retVal);
  return jsRetVal;
}
// pseudoClass HdrHistogram definition end //
// pseudoClass HdrHistogramIterator definition begin //

Napi::Value HdrHistogramIterator::hdr_iter_init_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_iter * iter = 0;
  const struct hdr_histogram * h = 0;
  hdr_iter_init (iter, h);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogramIterator::hdr_iter_next_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_iter * iter = 0;
  _Bool retVal = hdr_iter_next (iter);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogramIterator::hdr_iter_percentile_init_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_iter * iter = 0;
  const struct hdr_histogram * h = 0;
  int ticks_per_half_distance = getNumber<int> (info, 2);
  hdr_iter_percentile_init (iter, h, ticks_per_half_distance);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogramIterator::hdr_iter_recorded_init_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_iter * iter = 0;
  const struct hdr_histogram * h = 0;
  hdr_iter_recorded_init (iter, h);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}

Napi::Value HdrHistogramIterator::hdr_iter_linear_init_binding (const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  struct hdr_iter * iter = 0;
  const struct hdr_histogram * h = 0;
  long long value_units_per_bucket = getNumber<long long> (info, 2);
  hdr_iter_linear_init (iter, h, value_units_per_bucket);
  Napi::Value jsRetVal = env.Undefined();
  return jsRetVal;
}
// pseudoClass HdrHistogramIterator definition end //