// 2020-04-23T14:14:53.614-07:00 binding hdr_histogram.c (GenerateDeclarations)
// Generated by inspiredware's Binding Toolkit — www.inspiredware.com

#include <napi.h>
using namespace Napi;

// pseudoClass HdrHistogram declaration begin //
Value hdr_reset_internal_counters_binding (const CallbackInfo& info);
Value hdr_init_binding (const CallbackInfo& info);
Value hdr_close_binding (const CallbackInfo& info);
Value hdr_reset_binding (const CallbackInfo& info);
Value hdr_get_memory_size_binding (const CallbackInfo& info);
Value hdr_record_value_binding (const CallbackInfo& info);
Value hdr_record_value_atomic_binding (const CallbackInfo& info);
Value hdr_record_values_binding (const CallbackInfo& info);
Value hdr_record_values_atomic_binding (const CallbackInfo& info);
Value hdr_record_corrected_value_binding (const CallbackInfo& info);
Value hdr_record_corrected_value_atomic_binding (const CallbackInfo& info);
Value hdr_record_corrected_values_binding (const CallbackInfo& info);
Value hdr_record_corrected_values_atomic_binding (const CallbackInfo& info);
Value hdr_add_binding (const CallbackInfo& info);
Value hdr_max_binding (const CallbackInfo& info);
Value hdr_min_binding (const CallbackInfo& info);
Value hdr_value_at_percentile_binding (const CallbackInfo& info);
Value hdr_mean_binding (const CallbackInfo& info);
Value hdr_stddev_binding (const CallbackInfo& info);
Value hdr_values_are_equivalent_binding (const CallbackInfo& info);
Value hdr_lowest_equivalent_value_binding (const CallbackInfo& info);
Value hdr_count_at_value_binding (const CallbackInfo& info);
// pseudoClass HdrHistogram declaration end //
// pseudoClass HdrHistogramIterator declaration begin //
Value hdr_iter_init_binding (const CallbackInfo& info);
Value hdr_iter_next_binding (const CallbackInfo& info);
Value hdr_iter_percentile_init_binding (const CallbackInfo& info);
Value hdr_iter_recorded_init_binding (const CallbackInfo& info);
Value hdr_iter_linear_init_binding (const CallbackInfo& info);
// pseudoClass HdrHistogramIterator declaration end //